/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NgsiV2) {
      root.NgsiV2 = {};
    }
    root.NgsiV2.OpqueryExpression = factory(root.NgsiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OpqueryExpression model module.
   * @module model/OpqueryExpression
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>OpqueryExpression</code>.
   * @alias module:model/OpqueryExpression
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>OpqueryExpression</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OpqueryExpression} obj Optional instance to populate.
   * @return {module:model/OpqueryExpression} The populated <code>OpqueryExpression</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('q')) {
        obj['q'] = ApiClient.convertToType(data['q'], 'String');
      }
      if (data.hasOwnProperty('mq')) {
        obj['mq'] = ApiClient.convertToType(data['mq'], 'String');
      }
      if (data.hasOwnProperty('georel')) {
        obj['georel'] = ApiClient.convertToType(data['georel'], 'String');
      }
      if (data.hasOwnProperty('geometry')) {
        obj['geometry'] = ApiClient.convertToType(data['geometry'], 'String');
      }
      if (data.hasOwnProperty('coords')) {
        obj['coords'] = ApiClient.convertToType(data['coords'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} q
   */
  exports.prototype['q'] = undefined;
  /**
   * @member {String} mq
   */
  exports.prototype['mq'] = undefined;
  /**
   * @member {String} georel
   */
  exports.prototype['georel'] = undefined;
  /**
   * @member {String} geometry
   */
  exports.prototype['geometry'] = undefined;
  /**
   * @member {String} coords
   */
  exports.prototype['coords'] = undefined;



  return exports;
}));


