/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OpqueryExpression', 'model/QueryPattern'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OpqueryExpression'), require('./QueryPattern'));
  } else {
    // Browser globals (root is window)
    if (!root.NgsiV2) {
      root.NgsiV2 = {};
    }
    root.NgsiV2.Query = factory(root.NgsiV2.ApiClient, root.NgsiV2.OpqueryExpression, root.NgsiV2.QueryPattern);
  }
}(this, function(ApiClient, OpqueryExpression, QueryPattern) {
  'use strict';




  /**
   * The Query model module.
   * @module model/Query
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Query</code>.
   * @alias module:model/Query
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Query</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Query} obj Optional instance to populate.
   * @return {module:model/Query} The populated <code>Query</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('entities')) {
        obj['entities'] = ApiClient.convertToType(data['entities'], [QueryPattern]);
      }
      if (data.hasOwnProperty('attrs')) {
        obj['attrs'] = ApiClient.convertToType(data['attrs'], ['String']);
      }
      if (data.hasOwnProperty('expression')) {
        obj['expression'] = OpqueryExpression.constructFromObject(data['expression']);
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = ApiClient.convertToType(data['metadata'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/QueryPattern>} entities
   */
  exports.prototype['entities'] = undefined;
  /**
   * @member {Array.<String>} attrs
   */
  exports.prototype['attrs'] = undefined;
  /**
   * @member {module:model/OpqueryExpression} expression
   */
  exports.prototype['expression'] = undefined;
  /**
   * @member {Array.<String>} metadata
   */
  exports.prototype['metadata'] = undefined;



  return exports;
}));


