/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NgsiV2) {
      root.NgsiV2 = {};
    }
    root.NgsiV2.RegistrationResponseForwardingInformation = factory(root.NgsiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RegistrationResponseForwardingInformation model module.
   * @module model/RegistrationResponseForwardingInformation
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>RegistrationResponseForwardingInformation</code>.
   * @alias module:model/RegistrationResponseForwardingInformation
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>RegistrationResponseForwardingInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegistrationResponseForwardingInformation} obj Optional instance to populate.
   * @return {module:model/RegistrationResponseForwardingInformation} The populated <code>RegistrationResponseForwardingInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('timeSent')) {
        obj['timeSent'] = ApiClient.convertToType(data['timeSent'], 'Number');
      }
      if (data.hasOwnProperty('lastForwarding')) {
        obj['lastForwarding'] = ApiClient.convertToType(data['lastForwarding'], 'Date');
      }
      if (data.hasOwnProperty('lastFailure')) {
        obj['lastFailure'] = ApiClient.convertToType(data['lastFailure'], 'Date');
      }
      if (data.hasOwnProperty('lastSuccess')) {
        obj['lastSuccess'] = ApiClient.convertToType(data['lastSuccess'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Number} timeSent
   */
  exports.prototype['timeSent'] = undefined;
  /**
   * @member {Date} lastForwarding
   */
  exports.prototype['lastForwarding'] = undefined;
  /**
   * @member {Date} lastFailure
   */
  exports.prototype['lastFailure'] = undefined;
  /**
   * @member {Date} lastSuccess
   */
  exports.prototype['lastSuccess'] = undefined;



  return exports;
}));


