/**
 * ngsi-v2-extension-timeseries
 * An API extending NGSI V2 to support timeseries
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NgsiV2ExtensionTimeseries) {
      root.NgsiV2ExtensionTimeseries = {};
    }
    root.NgsiV2ExtensionTimeseries.RetrieveEntityAttributesResponse = factory(root.NgsiV2ExtensionTimeseries.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RetrieveEntityAttributesResponse model module.
   * @module model/RetrieveEntityAttributesResponse
   * @version v2
   */

  /**
   * Constructs a new <code>RetrieveEntityAttributesResponse</code>.
   * @alias module:model/RetrieveEntityAttributesResponse
   * @class
   * @param temperature {Object} 
   * @param humidity {Object} 
   * @param location {Object} 
   */
  var exports = function(temperature, humidity, location) {
    var _this = this;

    _this['temperature'] = temperature;
    _this['humidity'] = humidity;
    _this['location'] = location;
  };

  /**
   * Constructs a <code>RetrieveEntityAttributesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RetrieveEntityAttributesResponse} obj Optional instance to populate.
   * @return {module:model/RetrieveEntityAttributesResponse} The populated <code>RetrieveEntityAttributesResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('temperature')) {
        obj['temperature'] = ApiClient.convertToType(data['temperature'], Object);
      }
      if (data.hasOwnProperty('humidity')) {
        obj['humidity'] = ApiClient.convertToType(data['humidity'], Object);
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Object} temperature
   */
  exports.prototype['temperature'] = undefined;
  /**
   * @member {Object} humidity
   */
  exports.prototype['humidity'] = undefined;
  /**
   * @member {Object} location
   */
  exports.prototype['location'] = undefined;



  return exports;
}));


