/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SubscriptionNotificationHttp', 'model/SubscriptionNotificationHttpCustom'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SubscriptionNotificationHttp'), require('./SubscriptionNotificationHttpCustom'));
  } else {
    // Browser globals (root is window)
    if (!root.NgsiV2) {
      root.NgsiV2 = {};
    }
    root.NgsiV2.SubscriptionNotification = factory(root.NgsiV2.ApiClient, root.NgsiV2.SubscriptionNotificationHttp, root.NgsiV2.SubscriptionNotificationHttpCustom);
  }
}(this, function(ApiClient, SubscriptionNotificationHttp, SubscriptionNotificationHttpCustom) {
  'use strict';




  /**
   * The SubscriptionNotification model module.
   * @module model/SubscriptionNotification
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SubscriptionNotification</code>.
   * @alias module:model/SubscriptionNotification
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>SubscriptionNotification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionNotification} obj Optional instance to populate.
   * @return {module:model/SubscriptionNotification} The populated <code>SubscriptionNotification</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('attrs')) {
        obj['attrs'] = ApiClient.convertToType(data['attrs'], 'String');
      }
      if (data.hasOwnProperty('exceptAttrs')) {
        obj['exceptAttrs'] = ApiClient.convertToType(data['exceptAttrs'], 'String');
      }
      if (data.hasOwnProperty('http')) {
        obj['http'] = SubscriptionNotificationHttp.constructFromObject(data['http']);
      }
      if (data.hasOwnProperty('httpCustom')) {
        obj['httpCustom'] = SubscriptionNotificationHttpCustom.constructFromObject(data['httpCustom']);
      }
    }
    return obj;
  }

  /**
   * @member {String} attrs
   */
  exports.prototype['attrs'] = undefined;
  /**
   * @member {String} exceptAttrs
   */
  exports.prototype['exceptAttrs'] = undefined;
  /**
   * @member {module:model/SubscriptionNotificationHttp} http
   */
  exports.prototype['http'] = undefined;
  /**
   * @member {module:model/SubscriptionNotificationHttpCustom} httpCustom
   */
  exports.prototype['httpCustom'] = undefined;



  return exports;
}));


