/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SubscriptionNotification', 'model/SubscriptionSubject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SubscriptionNotification'), require('./SubscriptionSubject'));
  } else {
    // Browser globals (root is window)
    if (!root.NgsiV2) {
      root.NgsiV2 = {};
    }
    root.NgsiV2.Subscription = factory(root.NgsiV2.ApiClient, root.NgsiV2.SubscriptionNotification, root.NgsiV2.SubscriptionSubject);
  }
}(this, function(ApiClient, SubscriptionNotification, SubscriptionSubject) {
  'use strict';




  /**
   * The Subscription model module.
   * @module model/Subscription
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Subscription</code>.
   * @alias module:model/Subscription
   * @class
   * @param id {String} 
   * @param subject {module:model/SubscriptionSubject} 
   * @param notification {module:model/SubscriptionNotification} 
   */
  var exports = function(id, subject, notification) {
    var _this = this;

    _this['id'] = id;

    _this['subject'] = subject;
    _this['notification'] = notification;



  };

  /**
   * Constructs a <code>Subscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Subscription} obj Optional instance to populate.
   * @return {module:model/Subscription} The populated <code>Subscription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('subject')) {
        obj['subject'] = SubscriptionSubject.constructFromObject(data['subject']);
      }
      if (data.hasOwnProperty('notification')) {
        obj['notification'] = SubscriptionNotification.constructFromObject(data['notification']);
      }
      if (data.hasOwnProperty('expires')) {
        obj['expires'] = ApiClient.convertToType(data['expires'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('throttling')) {
        obj['throttling'] = ApiClient.convertToType(data['throttling'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/SubscriptionSubject} subject
   */
  exports.prototype['subject'] = undefined;
  /**
   * @member {module:model/SubscriptionNotification} notification
   */
  exports.prototype['notification'] = undefined;
  /**
   * @member {Date} expires
   */
  exports.prototype['expires'] = undefined;
  /**
   * @member {module:model/Subscription.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Number} throttling
   */
  exports.prototype['throttling'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "active"
     * @const
     */
    "active": "active",
    /**
     * value: "inactive"
     * @const
     */
    "inactive": "inactive"  };


  return exports;
}));


