/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QueryPattern', 'model/SubscriptionSubjectConditions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./QueryPattern'), require('./SubscriptionSubjectConditions'));
  } else {
    // Browser globals (root is window)
    if (!root.NgsiV2) {
      root.NgsiV2 = {};
    }
    root.NgsiV2.SubscriptionSubject = factory(root.NgsiV2.ApiClient, root.NgsiV2.QueryPattern, root.NgsiV2.SubscriptionSubjectConditions);
  }
}(this, function(ApiClient, QueryPattern, SubscriptionSubjectConditions) {
  'use strict';




  /**
   * The SubscriptionSubject model module.
   * @module model/SubscriptionSubject
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SubscriptionSubject</code>.
   * @alias module:model/SubscriptionSubject
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SubscriptionSubject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionSubject} obj Optional instance to populate.
   * @return {module:model/SubscriptionSubject} The populated <code>SubscriptionSubject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('entities')) {
        obj['entities'] = ApiClient.convertToType(data['entities'], [QueryPattern]);
      }
      if (data.hasOwnProperty('conditions')) {
        obj['conditions'] = SubscriptionSubjectConditions.constructFromObject(data['conditions']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/QueryPattern>} entities
   */
  exports.prototype['entities'] = undefined;
  /**
   * @member {module:model/SubscriptionSubjectConditions} conditions
   */
  exports.prototype['conditions'] = undefined;



  return exports;
}));


