/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NgsiV2) {
      root.NgsiV2 = {};
    }
    root.NgsiV2.SubscriptionNotificationHttpCustom = factory(root.NgsiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SubscriptionNotificationHttpCustom model module.
   * @module model/SubscriptionNotificationHttpCustom
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SubscriptionNotificationHttpCustom</code>.
   * @alias module:model/SubscriptionNotificationHttpCustom
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>SubscriptionNotificationHttpCustom</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionNotificationHttpCustom} obj Optional instance to populate.
   * @return {module:model/SubscriptionNotificationHttpCustom} The populated <code>SubscriptionNotificationHttpCustom</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('method')) {
        obj['method'] = ApiClient.convertToType(data['method'], 'String');
      }
      if (data.hasOwnProperty('qs')) {
        obj['qs'] = ApiClient.convertToType(data['qs'], Object);
      }
      if (data.hasOwnProperty('headers')) {
        obj['headers'] = ApiClient.convertToType(data['headers'], Object);
      }
      if (data.hasOwnProperty('payload')) {
        obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {module:model/SubscriptionNotificationHttpCustom.MethodEnum} method
   */
  exports.prototype['method'] = undefined;
  /**
   * @member {Object} qs
   */
  exports.prototype['qs'] = undefined;
  /**
   * @member {Object} headers
   */
  exports.prototype['headers'] = undefined;
  /**
   * @member {String} payload
   */
  exports.prototype['payload'] = undefined;


  /**
   * Allowed values for the <code>method</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MethodEnum = {
    /**
     * value: "GET"
     * @const
     */
    "GET": "GET",
    /**
     * value: "PUT"
     * @const
     */
    "PUT": "PUT",
    /**
     * value: "POST"
     * @const
     */
    "POST": "POST",
    /**
     * value: "DELETE"
     * @const
     */
    "DELETE": "DELETE",
    /**
     * value: "PATCH"
     * @const
     */
    "PATCH": "PATCH",
    /**
     * value: "HEAD"
     * @const
     */
    "HEAD": "HEAD",
    /**
     * value: "OPTIONS"
     * @const
     */
    "OPTIONS": "OPTIONS",
    /**
     * value: "TRACE"
     * @const
     */
    "TRACE": "TRACE",
    /**
     * value: "CONNECT"
     * @const
     */
    "CONNECT": "CONNECT"  };


  return exports;
}));


