/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NgsiV2);
  }
}(this, function(expect, NgsiV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NgsiV2.OpqueryExpression();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OpqueryExpression', function() {
    it('should create an instance of OpqueryExpression', function() {
      // uncomment below and update the code to test OpqueryExpression
      //var instane = new NgsiV2.OpqueryExpression();
      //expect(instance).to.be.a(NgsiV2.OpqueryExpression);
    });

    it('should have the property q (base name: "q")', function() {
      // uncomment below and update the code to test the property q
      //var instane = new NgsiV2.OpqueryExpression();
      //expect(instance).to.be();
    });

    it('should have the property mq (base name: "mq")', function() {
      // uncomment below and update the code to test the property mq
      //var instane = new NgsiV2.OpqueryExpression();
      //expect(instance).to.be();
    });

    it('should have the property georel (base name: "georel")', function() {
      // uncomment below and update the code to test the property georel
      //var instane = new NgsiV2.OpqueryExpression();
      //expect(instance).to.be();
    });

    it('should have the property geometry (base name: "geometry")', function() {
      // uncomment below and update the code to test the property geometry
      //var instane = new NgsiV2.OpqueryExpression();
      //expect(instance).to.be();
    });

    it('should have the property coords (base name: "coords")', function() {
      // uncomment below and update the code to test the property coords
      //var instane = new NgsiV2.OpqueryExpression();
      //expect(instance).to.be();
    });

  });

}));
