/**
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APIEntryPoint', 'model/Attribute', 'model/AttributeValue', 'model/BatchOperation', 'model/DataProvided', 'model/DataProvidedExpression', 'model/Entity', 'model/EntityType', 'model/ErrorResponse', 'model/OpqueryExpression', 'model/Provider', 'model/Query', 'model/QueryPattern', 'model/Registration', 'model/RegistrationResponse', 'model/RegistrationResponseForwardingInformation', 'model/Subscription', 'model/SubscriptionNotification', 'model/SubscriptionNotificationHttp', 'model/SubscriptionNotificationHttpCustom', 'model/SubscriptionSubject', 'model/SubscriptionSubjectConditions', 'model/UpdateSubscriptionResponse', '/APIEntryPointApi', '/AttributeValueApi', '/AttributesApi', '/BatchOperationsApi', '/EntitiesApi', '/RegistrationsApi', '/SubscriptionsApi', '/TypesApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/APIEntryPoint'), require('./model/Attribute'), require('./model/AttributeValue'), require('./model/BatchOperation'), require('./model/DataProvided'), require('./model/DataProvidedExpression'), require('./model/Entity'), require('./model/EntityType'), require('./model/ErrorResponse'), require('./model/OpqueryExpression'), require('./model/Provider'), require('./model/Query'), require('./model/QueryPattern'), require('./model/Registration'), require('./model/RegistrationResponse'), require('./model/RegistrationResponseForwardingInformation'), require('./model/Subscription'), require('./model/SubscriptionNotification'), require('./model/SubscriptionNotificationHttp'), require('./model/SubscriptionNotificationHttpCustom'), require('./model/SubscriptionSubject'), require('./model/SubscriptionSubjectConditions'), require('./model/UpdateSubscriptionResponse'), require('.//APIEntryPointApi'), require('.//AttributeValueApi'), require('.//AttributesApi'), require('.//BatchOperationsApi'), require('.//EntitiesApi'), require('.//RegistrationsApi'), require('.//SubscriptionsApi'), require('.//TypesApi'));
  }
}(function(ApiClient, APIEntryPoint, Attribute, AttributeValue, BatchOperation, DataProvided, DataProvidedExpression, Entity, EntityType, ErrorResponse, OpqueryExpression, Provider, Query, QueryPattern, Registration, RegistrationResponse, RegistrationResponseForwardingInformation, Subscription, SubscriptionNotification, SubscriptionNotificationHttp, SubscriptionNotificationHttpCustom, SubscriptionSubject, SubscriptionSubjectConditions, UpdateSubscriptionResponse, APIEntryPointApi, AttributeValueApi, AttributesApi, BatchOperationsApi, EntitiesApi, RegistrationsApi, SubscriptionsApi, TypesApi) {
  'use strict';

  /**
   * Javascript Client for NGSI v2.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var NgsiV2 = require('index'); // See note below*.
   * var xxxSvc = new NgsiV2.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new NgsiV2.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new NgsiV2.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new NgsiV2.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The APIEntryPoint model constructor.
     * @property {module:model/APIEntryPoint}
     */
    APIEntryPoint: APIEntryPoint,
    /**
     * The Attribute model constructor.
     * @property {module:model/Attribute}
     */
    Attribute: Attribute,
    /**
     * The AttributeValue model constructor.
     * @property {module:model/AttributeValue}
     */
    AttributeValue: AttributeValue,
    /**
     * The BatchOperation model constructor.
     * @property {module:model/BatchOperation}
     */
    BatchOperation: BatchOperation,
    /**
     * The DataProvided model constructor.
     * @property {module:model/DataProvided}
     */
    DataProvided: DataProvided,
    /**
     * The DataProvidedExpression model constructor.
     * @property {module:model/DataProvidedExpression}
     */
    DataProvidedExpression: DataProvidedExpression,
    /**
     * The Entity model constructor.
     * @property {module:model/Entity}
     */
    Entity: Entity,
    /**
     * The EntityType model constructor.
     * @property {module:model/EntityType}
     */
    EntityType: EntityType,
    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The OpqueryExpression model constructor.
     * @property {module:model/OpqueryExpression}
     */
    OpqueryExpression: OpqueryExpression,
    /**
     * The Provider model constructor.
     * @property {module:model/Provider}
     */
    Provider: Provider,
    /**
     * The Query model constructor.
     * @property {module:model/Query}
     */
    Query: Query,
    /**
     * The QueryPattern model constructor.
     * @property {module:model/QueryPattern}
     */
    QueryPattern: QueryPattern,
    /**
     * The Registration model constructor.
     * @property {module:model/Registration}
     */
    Registration: Registration,
    /**
     * The RegistrationResponse model constructor.
     * @property {module:model/RegistrationResponse}
     */
    RegistrationResponse: RegistrationResponse,
    /**
     * The RegistrationResponseForwardingInformation model constructor.
     * @property {module:model/RegistrationResponseForwardingInformation}
     */
    RegistrationResponseForwardingInformation: RegistrationResponseForwardingInformation,
    /**
     * The Subscription model constructor.
     * @property {module:model/Subscription}
     */
    Subscription: Subscription,
    /**
     * The SubscriptionNotification model constructor.
     * @property {module:model/SubscriptionNotification}
     */
    SubscriptionNotification: SubscriptionNotification,
    /**
     * The SubscriptionNotificationHttp model constructor.
     * @property {module:model/SubscriptionNotificationHttp}
     */
    SubscriptionNotificationHttp: SubscriptionNotificationHttp,
    /**
     * The SubscriptionNotificationHttpCustom model constructor.
     * @property {module:model/SubscriptionNotificationHttpCustom}
     */
    SubscriptionNotificationHttpCustom: SubscriptionNotificationHttpCustom,
    /**
     * The SubscriptionSubject model constructor.
     * @property {module:model/SubscriptionSubject}
     */
    SubscriptionSubject: SubscriptionSubject,
    /**
     * The SubscriptionSubjectConditions model constructor.
     * @property {module:model/SubscriptionSubjectConditions}
     */
    SubscriptionSubjectConditions: SubscriptionSubjectConditions,
    /**
     * The UpdateSubscriptionResponse model constructor.
     * @property {module:model/UpdateSubscriptionResponse}
     */
    UpdateSubscriptionResponse: UpdateSubscriptionResponse,
    /**
     * The APIEntryPointApi service constructor.
     * @property {module:/APIEntryPointApi}
     */
    APIEntryPointApi: APIEntryPointApi,
    /**
     * The AttributeValueApi service constructor.
     * @property {module:/AttributeValueApi}
     */
    AttributeValueApi: AttributeValueApi,
    /**
     * The AttributesApi service constructor.
     * @property {module:/AttributesApi}
     */
    AttributesApi: AttributesApi,
    /**
     * The BatchOperationsApi service constructor.
     * @property {module:/BatchOperationsApi}
     */
    BatchOperationsApi: BatchOperationsApi,
    /**
     * The EntitiesApi service constructor.
     * @property {module:/EntitiesApi}
     */
    EntitiesApi: EntitiesApi,
    /**
     * The RegistrationsApi service constructor.
     * @property {module:/RegistrationsApi}
     */
    RegistrationsApi: RegistrationsApi,
    /**
     * The SubscriptionsApi service constructor.
     * @property {module:/SubscriptionsApi}
     */
    SubscriptionsApi: SubscriptionsApi,
    /**
     * The TypesApi service constructor.
     * @property {module:/TypesApi}
     */
    TypesApi: TypesApi
  };

  return exports;
}));
