/**
 * ngsi-v2-extension-timeseries
 * An API extending NGSI V2 to support timeseries
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NgsiV2ExtensionTimeseries);
  }
}(this, function(expect, NgsiV2ExtensionTimeseries) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NgsiV2ExtensionTimeseries.EntitiesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EntitiesApi', function() {
    describe('createEntity', function() {
      it('should call createEntity successfully', function(done) {
        //uncomment below and update the code to test createEntity
        //instance.createEntity(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listEntities', function() {
      it('should call listEntities successfully', function(done) {
        //uncomment below and update the code to test listEntities
        //instance.listEntities(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeEntity', function() {
      it('should call removeEntity successfully', function(done) {
        //uncomment below and update the code to test removeEntity
        //instance.removeEntity(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceAllEntityAttributes', function() {
      it('should call replaceAllEntityAttributes successfully', function(done) {
        //uncomment below and update the code to test replaceAllEntityAttributes
        //instance.replaceAllEntityAttributes(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveEntity', function() {
      it('should call retrieveEntity successfully', function(done) {
        //uncomment below and update the code to test retrieveEntity
        //instance.retrieveEntity(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveEntityAttributes', function() {
      it('should call retrieveEntityAttributes successfully', function(done) {
        //uncomment below and update the code to test retrieveEntityAttributes
        //instance.retrieveEntityAttributes(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateExistingEntityAttributes', function() {
      it('should call updateExistingEntityAttributes successfully', function(done) {
        //uncomment below and update the code to test updateExistingEntityAttributes
        //instance.updateExistingEntityAttributes(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateOrAppendEntityAttributes', function() {
      it('should call updateOrAppendEntityAttributes successfully', function(done) {
        //uncomment below and update the code to test updateOrAppendEntityAttributes
        //instance.updateOrAppendEntityAttributes(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
